# Generated by Django 2.2.7 on 2019-12-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lengua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Lengua')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Tipo de Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nombreLugar', models.TextField(verbose_name='Nombre del lugar')),
                ('pais', models.TextField(verbose_name='Pais')),
                ('lenguajes', models.ManyToManyField(to='main.Lengua')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Municipio')),
                ('tipoEvento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.TipoEvento')),
            ],
        ),
    ]
